AWSTemplateFormatVersion: '2010-09-09'
Description: 'PG&E Bill Split Automation - Simple AWS Infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: 'pge-bill-automation'
    Description: 'Name for the project resources'
  
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'prod']
    Description: 'Environment (dev or prod)'

Resources:
  # S3 Bucket for PDF storage
  PDFBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-pdfs-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # DynamoDB Table for Bills
  BillsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-bills-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: 'bill_id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'bill_id'
          KeyType: 'HASH'

  # Secrets Manager for configuration
  ConfigSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}-config-${Environment}'
      Description: 'Configuration settings for PG&E automation'
      SecretString: !Sub |
        {
          "gmail_user": "andrewhting@gmail.com",
          "roommate_email": "loushic@gmail.com",
          "my_email": "andrewhting@gmail.com",
          "roommate_venmo": "UshiLo",
          "my_venmo": "andrewhting",
          "my_phone": "+19298884132",
          "roommate_split_ratio": 0.333333,
          "my_split_ratio": 0.666667,
          "test_mode": true,
          "enable_email_notifications": true,
          "enable_text_messaging": true
        }

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: 'PGEAutomationPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # DynamoDB permissions
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt BillsTable.Arn
              # S3 permissions
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub 'arn:aws:s3:::${PDFBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub 'arn:aws:s3:::${PDFBucket}'
              # SES permissions
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: '*'
              # SNS permissions for SMS
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: '*'
              # Secrets Manager permissions
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref ConfigSecrets

  # Lambda Function
  AutomationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-automation-${Environment}'
      Runtime: python3.9
      Handler: lambda_handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 900  # 15 minutes
      MemorySize: 512
      Environment:
        Variables:
          BILLS_TABLE: !Ref BillsTable
          PDF_BUCKET: !Ref PDFBucket
          SECRETS_ARN: !Ref ConfigSecrets
          ENVIRONMENT: !Ref Environment
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Placeholder - will be replaced with actual code'
              }

Outputs:
  LambdaFunctionArn:
    Description: 'ARN of the Lambda function'
    Value: !GetAtt AutomationFunction.Arn

  S3BucketName:
    Description: 'Name of the S3 bucket for PDFs'
    Value: !Ref PDFBucket

  BillsTableName:
    Description: 'Name of the DynamoDB bills table'
    Value: !Ref BillsTable